version: '3.8'
services:
  dev-db:
    image: postgres:15.3
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: bankuish
      POSTGRES_PASSWORD: bankuish
      POSTGRES_DB: bankuish
    networks:
      - bankuish-network

networks:
  bankuish-network: 
